---
abstract: 'testing TCP program'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-TCP
provides:
  Net::EmptyPort:
    file: lib/Net/EmptyPort.pm
    version: 0
  Test::TCP:
    file: lib/Test/TCP.pm
    version: 1.24
  Test::TCP::CheckPort:
    file: lib/Test/TCP/CheckPort.pm
    version: 0
requires:
  IO::Socket::INET: 0
  Test::SharedFork: 0.19
  perl: 5.00800
resources:
  bugtracker: https://github.com/tokuhirom/Test-TCP/issues
  homepage: https://github.com/tokuhirom/Test-TCP
  repository: git://github.com/tokuhirom/Test-TCP.git
version: 1.24
