---
abstract: 'testing TCP program'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: test-tcp
provides: {}
requires:
  IO::Socket::INET: 0
  Test::SharedFork: 0.19
  perl: 5.00800
resources:
  bugtracker: https://github.com/tokuhirom/test-tcp/issues
  homepage: https://github.com/tokuhirom/test-tcp
  repository: git://github.com/tokuhirom/test-tcp.git
version: 1.22
